%
% Created by Feng, W.P., @ GU, 20120825
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
gmt_outps     = 'T004GAMMA.ps';
objdir        = '.';
prefix_images = 'gamma_*.phs';
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
numraw = 3;
numcol = 3;
xwidth = 4.15;
yhigh  = 3.9;
gmt_mregion = ' -R95.7316/96.8791/32.5059/33.9734 ';
gmt_mregion = ' -R95.5083/97.0425/32.8634/34.0609 ';
%
xmin        = 96.03;%95.5083;
xmax        = 97.5158;%97.0425;
ymin        = 32.5067;%32.8634;
ymax        = 33.6425;%34.0609;
gmt_mregion = [' -R',num2str(xmin),'/',num2str(xmax),'/',...
                     num2str(ymin),'/',num2str(ymax),' '];
%
gmt_cptname = 'velocity_power.cpt';
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ints = dir(prefix_images);
%
gmt_gmtset('gmt_paper_media','A0');
%
gmt_makecpt('gmt_zstart',-3.15,'gmt_zend',3.15,...
            'gmt_cptname',gmt_cptname);
%
for ni = 1:numel(ints)
    cint      = ints(ni).name;
    fcint     = [objdir,'/',cint];
    [~,times] = fileparts(cint);
    %ids   = strfind(times,'-T488');
    %times = [times(1:ids-1),'-T488'];
    %
    info  = sim_roirsc([fcint,'.rsc']);
    [xoff,yoff,iscon,isov] = gmt_sortplot(numraw,numcol,ni,xwidth,yhigh);
    if ni == numel(ints)
        iscon = 0;
    end
    %
    gmt_img2ps(fcint,....
        'gmt_mregion',gmt_mregion,...
        'gmt_xoff',xoff,...
        'gmt_yoff',yoff,...
        'gmt_outps',gmt_outps,....
        'gmt_iscon',1,...
        'gmt_isov',isov,...
        'gmt_scale',2,...
        'gmt_snew','snew',...
        'iswrap',1,...
        'gmt_cptname',gmt_cptname,...
        'minwrap',-3.14,...
        'maxwrap', 3.14,...
        'gmt_colorbarxoffset','0.8i',...
        'gmt_colorbaryoffset','0.45i',...
        'gmt_colorbarwidth','0.1i',...
        'gmt_colorbarlength','1i',...
        'gmt_zinterv','3.14');
    %
    gmt_pstext(...
        'text_x',num2str(xmin+(xmax-xmin)*0.05),...
        'text_y',num2str(ymax-(ymax-ymin)*0.1),...
        'text_string',times,...
        'text_isov',1,...
        'text_iscon',iscon,...
        'text_outps',gmt_outps);
end