%
% A new version for batch plotting...
% By fWP, @IGPP of SIO, UCSD, 2013-11-28
%
ints         = dir('fft*.img');
%

faulttopo = 'geo_08mw63TOP.inp';
faultpoly = 'geo_08mw63POLY.inp';
%
numraw       = 3;
numcol       = 9;
xwidth       = [];
type         = 'prefix';
gmt_cptname  = gmt_cptdb('egg');
%
if exist(gmt_cptname,'file')
    colormapt     = gmt_importcpt(gmt_cptname);
else
    colormapt = [];
end
colormapt = [];%
if ~isnan(colormapt)
    backgroundcol = fix(colormapt(2,:).*255);
    foregroundcol = fix(colormapt(end-1,:).*255);
    backcol = [num2str(backgroundcol(1)),'/',...
        num2str(backgroundcol(2)),'/',...
        num2str(backgroundcol(3))];
    %
    forecol = [num2str(foregroundcol(1)),'/',...
        num2str(foregroundcol(2)),'/',...
        num2str(foregroundcol(3))];
else
    backcol = '0/0/0';
    forecol = '255/255/255';
end
gmt_outdpi    = 300;
gmt_zerovalue = [];
gmt_nanvalue  = [];
gmt_factor    = [];
gmt_cmconv    = 0;
gmt_version   = 5;
gmt_demgrd    = ys_datafile('dem');
gmt_outps     = 'Fig_smooth.ps';
gmt_unit      = 'Rad';
gmt_frame_width = '0.05i';
gmt_frame_width_value = 0.05;
%
gmt_gmtset('gmt_color_nan','255/255/255',...
    'gmt_paper_media','A0',...
    'gmt_annot_font_size_primary','8p',...
    'gmt_tick_length','0.05c',...
    'gmt_color_background',backcol,...
    'gmt_frame_width','0.05c',...
    'gmt_color_foreground',forecol,...
    'gmt_oblique_annotation','32' ,...
    'gmt_frame_width',gmt_frame_width);
%
%
ctitles       = {'a-1','a-2','a-3','b-1','b-2','b-3','c-1','c-2','c-3','d-1','d-2','d-3',...
    'e-1','e-2','e-3','f-1','f-2','f-3','g-1','g-2','g-3','h-1','h-2','h-3'};
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
xwid        = 2.5;
%
gmt_iswrap  = 0;
%
%
%
gmt_mul   = [...
    -5.6/(4*pi),-5.6/(4*pi),-5.6/(4*pi),...
    -5.6/(4*pi),-5.6/(4*pi),-5.6/(4*pi),...
    -5.6/(4*pi),-5.6/(4*pi),-5.6/(4*pi),...
    -5.6/(4*pi),-5.6/(4*pi),-5.6/(4*pi),...
    -5.6/(4*pi),-5.6/(4*pi),-5.6/(4*pi),...
    -23.23/(4*pi),-23.23/(4*pi),-23.23/(4*pi),...
    1,1,1];
wraprange = [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0.5,0.5,0.5];
wraprange        = wraprange.*1.25;
wraprange(19:21) = 0.5;
wraprange        = 3.14;%
iswrap           = [1,1,1,...
    1,1,1,...
    1,1,1,...
    1,1,1,...
    1,1,1,...
    1,1,1,...
    0,0,0];
iswrap = 1;%iswrap.*0;
%
%
outregion = [];
%times = load('time.txt');
for ni = 1:numel(ints)
    %
    if iscell(ints)
        cint = ints{ni};
    else
        cint  = ints(ni).name;
    end
    fcrsc = [cint,'.rsc'];
    fcint = cint;
    %
    if iscell(ints)
        scale       = gmt_img2xyratio([ints{1},'.rsc']);
    else
        scale       = gmt_img2xyratio([ints(1).name,'.rsc']);
    end
    yhigh = xwid.*scale*-1;
    %
    [~,bname] = fileparts(cint);
    %
    tm = textscan(bname,'%s','delimiter','_');
    tm = tm{1};
    if numel(tm)<4
        tm=tm{1};
    else
        tm = tm{4};
    end
    %
    %
    mtitle = [tm(5:end)];%%[num2str(times(notime+1)) ' yr'];
    %
    info         = sim_roirsc(fcrsc);
    [xoff,yoff,iscon,isov,gmt_snew] = gmt_sortplot(numraw,numcol,ni,xwid,yhigh);
    %
    if ni == numel(ints)
        iscon = 0;
    end
    %
    if gmt_cmconv == 1
        gmt_factor = info.wavelength/(4*pi)*100;
    end
    %
    outregion = gmt_img2ps(fcint,....
        'gmt_xoff',xoff,...
        'gmt_demgrd',gmt_demgrd,...
        'gmt_yoff',yoff,...
        'gmt_proj',[' -JM',num2str(xwid),'i'],...
        'gmt_outps',gmt_outps,....
        'gmt_iscon',1,...
        'gmt_isov',isov,...
        'gmt_colorn',gmt_cptname,...
        'gmt_nanvalue',100,...
        'gmt_axstep','0.5',...
        'gmt_aystep','0.5',...
        'gmt_snew',gmt_snew,...
        'iswrap',iswrap,...
        'gmt_cptname',[],...
        'minwrap',wraprange.*-1,...
        'maxwrap',wraprange,...
        'gmt_minwrap',wraprange.*-1,...
        'gmt_maxwrap',wraprange,...
        'gmt_colorbarxoffset','0.40i',...
        'gmt_colorbaryoffset','0.4i',...
        'gmt_colorbarwidth',  '0.07i',...
        'gmt_colorbarlength', '0.6i',...
        'gmt_outdpi',   gmt_outdpi,...
        'gmt_zinterv',  wraprange,...
        'gmt_unit',gmt_unit,...
        'gmt_mul',      1,...
        'gmt_version',  gmt_version);
    %
    gmt_psxy4line(faulttopo,...
        'outps',gmt_outps,...
        'gmt_faultstype',' -Sf0.35i/0.1irt:0.1i ',...)
        'isov',1,...
        'iscon',1,...
        'proj',' -J ',...
        'gmt_lwid','0.1c',...
        'linecolor',',255/10/10',...
        'mregion',' -R ');
    %
    gmt_psxy4line(faultpoly,...
        'outps',gmt_outps,...
        'gmt_faultstype',' ',...)
        'isov',1,...
        'iscon',1,...
        'proj',' -J ',...
        'gmt_lwid','0.03c',...
        'linecolor',',10/10/10',...
        'mregion',' -R ');
    gmt_pstext(...
        'text_x',num2str(outregion(1)+(outregion(2)-outregion(1))*0.001),...
        'text_y',num2str(outregion(4)-(outregion(4)-outregion(3))*0.09),...
        'text_string',mtitle,...
        'text_isov',1,...
        'text_iscon',iscon,...
        'gmt_outdpi',gmt_outdpi,...
        'text_outps',gmt_outps,...
        'gmt_version',gmt_version);
    if  iscon == 0
        return;
    end
end
%