%
%
%
% Figure obs,sim,res
%
% Developed by FWP, @ GU, 2013-03-28
%
gmt_outps  = 'Fig_x_20130328.ps';
%
gmt_demgrd = 'E:\TEMP\turkey_111023\turkey.img';
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
files   = {'../data/cosm/geo_20111010-20111026-TCOS_rmp.img',...
           '../simres/SIM_geo_20111010-20111026-TCOS_prev4.phs',...
           '../simres/RES_geo_20111010-20111026-TCOS_prev4.phs',....
           '../data/MAI/geo_20111010-20111026_azi.img',...
           '../simres/SIM_geo_20111010-20111026_azi_prev4_LOS.phs',...
           '../simres/RES_geo_20111010-20111026_azi_v1_ABCSIM.los'};
%
gmt_labels = {'(a)','(b)','(c)'};
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
proj         = '-JM4i';
gmt_xoff     = '4.1i';
gmt_yoff     = '5i';
iswrap       = 1;
minwrap      = -8.01;
maxwrap      =  8.01;
gmt_zinterv  = '8';
gmt_factor   = -3.1/(4*pi);
gmt_colorn   = 'D:\mdbase\users\others\gmt_mcodesv4\cpt\eastereggs.cpt';
gmt_cptname  = 'imgtk.cpt';
gmt_imgscale = 1;
gmt_lenscale = ' -Lfx3.4i/0.42i/0/10k+lkm+jt ';
gmt_demscale = '0.75';
gmt_textsize = '17';
gmt_roi      = [];
%
%
gmt_isov  = 0;
gmt_iscon = 0;
%
%%%%%%%%%%%%
gmt_makecpt(...
    'gmt_colorn',gmt_colorn,...
    'gmt_cptname',gmt_cptname,....
    'gmt_zstart',minwrap,....
    'gmt_zend',maxwrap);

%
gmt_gmtset(...
    'gmt_paper_media','A0',...
    'gmt_label_font_size','10',...
    'gmt_frame_width','0.05c');
%
regions = gmt_img2ps(....
    files{1},...
    'gmt_roi',gmt_roi,....
    'gmt_scale',  gmt_imgscale,...
    'gmt_demgrd', gmt_demgrd,...
    'gmt_cptname',gmt_cptname,...
    'gmt_factor', gmt_factor,...
    'gmt_colorn', gmt_colorn,...
    'gmt_outps',  gmt_outps,...
    'gmt_demdisplay',gmt_demscale,...
    'gmt_unit','cm',...
    'gmt_xoff', gmt_xoff,...
    'gmt_yoff', gmt_yoff,...
    'gmt_isov', gmt_isov,...
    'gmt_iscon',1,...
    'gmt_nanvalue',200,...
    'gmt_zerovalue',nan,...
    'gmt_snew','sNeW',...
    'iswrap', iswrap,...
    'minwrap',minwrap,...
    'maxwrap',maxwrap,...
    'gmt_lengthscale',gmt_lenscale,...
    'gmt_zinterv',gmt_zinterv);
 %
 gmt_pstext(...
     'text_x',num2str(     (regions(2)-regions(1))*0.01 + regions(1)),...
     'text_y',num2str(-1 * (regions(4)-regions(3))*0.05 + regions(4)),...
     'text_string',gmt_labels{1},...
     'text_isov',1,...
     'text_iscon',1,...
     'text_size',gmt_textsize,...
     'text_outps',gmt_outps);
 %
regions = gmt_img2ps(....
    files{2},...
    'gmt_scale',gmt_imgscale,...
    'gmt_demgrd',gmt_demgrd,...
    'gmt_cptname',gmt_cptname,...
    'gmt_factor',gmt_factor,...
    'gmt_colorn',gmt_colorn,...
    'gmt_outps',gmt_outps,...
    'gmt_xoff', gmt_xoff,...
    'gmt_yoff', '0i',...
    'gmt_isov', 1,...
    'gmt_iscon',1,...
    'gmt_nanvalue',200,...
    'gmt_zerovalue',nan,...
    'gmt_snew','sNew',...
    'iswrap', iswrap,...
    'gmt_demdisplay',gmt_demscale,...
    'minwrap',minwrap,...
    'maxwrap',maxwrap,...
    'gmt_zinterv',gmt_zinterv); 
gmt_pstext(...
     'text_x',num2str(     (regions(2)-regions(1))*0.01 + regions(1)),...
     'text_y',num2str(-1 * (regions(4)-regions(3))*0.05 + regions(4)),...
     'text_string',gmt_labels{2},...
     'text_isov',1,...
     'text_iscon',1,...
     'text_size',gmt_textsize,...
     'text_outps',gmt_outps);
 %
%
regions = gmt_img2ps(....
    files{3},...
    'gmt_scale',gmt_imgscale,...
    'gmt_demgrd',gmt_demgrd,...
    'gmt_cptname',gmt_cptname,...
    'gmt_factor',gmt_factor,...
    'gmt_colorn',gmt_colorn,...
    'gmt_outps',gmt_outps,...
    'gmt_xoff', gmt_xoff,...
    'gmt_yoff', '0i',...
    'gmt_isov', 1,...
    'gmt_iscon',1,...
    'gmt_nanvalue',200,...
    'gmt_demdisplay',gmt_demscale,...
    'gmt_zerovalue',nan,...
    'gmt_snew','sNEw',...
    'iswrap', iswrap,...
    'minwrap',minwrap,...
    'maxwrap',maxwrap,...
    'gmt_zinterv',gmt_zinterv); 
gmt_pstext(...
     'text_x',num2str(     (regions(2)-regions(1))*0.01 + regions(1)),...
     'text_y',num2str(-1 * (regions(4)-regions(3))*0.05 + regions(4)),...
     'text_string',gmt_labels{3},...
     'text_isov',1,...
     'text_iscon',gmt_iscon,...
     'text_size',gmt_textsize,...
     'text_outps',gmt_outps);