function gmt_vectors(ints,gmt_outps,varargin)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% A new version for batch plotting...
% By fWP, @IGPP of SIO, UCSD, 2013-11-28
% Updated by Feng, W.P., @ YJ, 2015-04-20
% -> make it available for GMT5.x
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if nargin < 1
    cphs = dir('geo*T*.phs');
    if numel(cphs) == 0
        return
    else
        ints = cphs;
        [~,bname] = fileparts(ints(1).name);
        gmt_outps = [bname,'.ps'];
    end
end
%
gmt_superiscon    = 0;
gmt_bound         = [];
faultpoly         = 'geo_08mw63POLY.inp';
gmt_isisoseismal  = 0;
islegend          = 1;
%
gmt_iscapital     = 1;
gmt_issarpoly     = 0;
numraw            = 4;
numcol            = 9;
intitle           = [];
% slip vector
gmt_sliplwid      = '0.75p';
gmt_slipscale     = '0.25';
gmt_sliplcolor    = ',200/0/0';
gmt_slipvecpar    = '9p';
gmt_slipselectinv = 5;
gmt_slipthreshold = 2;
%
gmt_oksar    = [];
%
gmt_slipinterval  = '2.5';
gmt_globalmapsize = '1.5i';
gmt_globalxoff    = '1.5i';
gmt_globalyoff    = '1.5i';
gmt_globaltype    = 'relief';
gmt_isglobal      = 0;
gmt_psize         = '0.2c';
gmt_lwid          = '0.01c';
gmt_inptcolortb   = gmt_cptdb('egg') ;%'seis';
gmt_ptmin         = 0;
gmt_ptmax         = 1;
gmt_ptlinecolor   = '255/255/255';
gmt_slipvecattr   = '+a35+n5';
%
gmt_ptinterv   = 0.1;
gmt_ptdata     = [];
%
% GPS Plotting Starts
gmt_isgps            = 0;
gmt_gpspsize         = '0.15c';
gmt_gpsfontcolor     = '50/50/50';
gmt_gpsfontbackcolor = '255/255/255';
%
gmt_gpsvellwid      = '0.5p';
gmt_gpsvelscale     = '0.25';
gmt_gpsvelcolor     = ',0/0/255';
gmt_gpsvelvecpar    = '5p+a60+g0/0/255+p1.1p+e';
gmt_gpsvelvecattr   = ' ';
gmt_lengthscale     = [];
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% aftershock
gmt_isaftershock    = 0;
%
% GPS plotting END
%
gmt_epsize    = '0.4c';
gmtepi        = [84.708,28.147];
gmt_cptname   = gmt_cptdb('egg');
gmt_outdpi    = 300;
gmt_version   = 5;
gmt_demgrd    = sar_dempath('SRTM');           % Provide a srtm data for background topographic relief
gmt_demiscolorbar = 0;
gmt_demunit       = '(m)';
gmt_demzinterv    = 1000;
gmt_unit                        = 'Rad';
gmt_title                       = '';                            % First Test using GMT5.x';
text_size                       = '9p';
text_fontcolor                  = 'black';
text_pen                        = '';
text_backcolor                  = '10/10/10';
text_edgewidth                  = '0.01i';
text_fillcolor                  = '50/50/50';

gmt_textscaley = 0.035;
gmt_textscalex = 0.0001;
%
gmt_frame_width                 = '0.02i';
gmt_frame_pen                   = '0.001i';
gmt_font_title                  = '13p,4,red';
gmt_annot_offset_primary        = '2p';
gmt_psscale_background_pen      = '0.03i';
gmt_psscale_background_fill     = '220/220/220';
gmt_psscale_background_offset   = '0.0250i';
gmt_psscale_background_offset_t = '0.0250i';
gmt_psscale_background_offset_b = '0.0150i';
gmt_psscale_background_offset_l = '0.0850i';
gmt_psscale_background_offset_r = '0.0350i';
gmt_faultstype                  = ' -Sf0.35i/0.1i+r+t+o0.1i ';
gmt_graddifusion                = 0.5;
gmt_azimuth2                    = 135;
gmt_azimuth1                    = 90;
gmt_scalecof                    = 1;
gmt_gradientmethod              = 'A';
gmt_demdisplay                  = '0.45';
gmt_inputformat                 = 'integer';
%
xwid                            = 2.5;
iswrap                          = 0;
minwrap                         = [];
maxwrap                         = [];
gmt_scale                       = 2;
gmt_axstep                      = '0.75';
gmt_aystep                      = '0.5';
gmt_minwrap                     = [];
gmt_maxwrap                     = [];
gmt_zinterv                     = [];
gmt_faulttop                    = [];
gmt_demcpt                      = [];
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Input parameters
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for ni = 1:2:numel(varargin)
    var = varargin{ni};
    val = varargin{ni+1};
    eval([var,'= val;']);
    %
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%
if isempty(gmt_faulttop)
    faulttopo = 'geo_08mw63TOP.inp';
else
    faulttopo = gmt_faulttop;
end
%
if isempty(gmt_minwrap)
    gmt_minwrap = -1*abs(wraprange);
end
if isempty(gmt_maxwrap)
    gmt_maxwrap = abs(wraprange);
end
if isempty(gmt_zinterv)
    gmt_zinterv = sum(abs([gmt_maxwrap,gmt_minwrap]))./2;
end
%
if isempty(minwrap)
    minwrap = gmt_minwrap;
end
%
if isempty(maxwrap)
    maxwrap = gmt_maxwrap;
end
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
backcol = '0/0/0';
forecol = '255/255/255';
%
%

if exist(gmt_demcpt,'file')
    colormapt     = gmt_importcpt(gmt_demcpt);
else
    colormapt = [];
end
%colormapt = [];%
if ~isnan(colormapt)
    backgroundcol = fix(colormapt(2,:).*255);
    foregroundcol = fix(colormapt(end-1,:).*255);
    backcol = [num2str(backgroundcol(1)),'/',...
        num2str(backgroundcol(2)),'/',...
        num2str(backgroundcol(3))];
    %
    forecol = [num2str(foregroundcol(1)),'/',...
        num2str(foregroundcol(2)),'/',...
        num2str(foregroundcol(3))];
else
    backcol = '0/0/0';
    forecol = '255/255/255';
end
%
gmt_gmtset('gmt_color_nan',               '255/255/255',...
    'gmt_paper_media',             'A0',...
    'gmt_annot_font_size_primary', '4.5p',...
    'gmt_tick_length',             '0.05c',...
    'gmt_color_background',        backcol,...
    'gmt_frame_pen',               gmt_frame_pen,...
    'gmt_annot_offset_primary',    gmt_annot_offset_primary,...
    'gmt_color_foreground',        forecol,...
    'gmt_oblique_annotation',      '32' ,...
    'gmt_frame_width',             gmt_frame_width,...
    'gmt_font_title',              gmt_font_title);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
for ni = 1:numel(ints)
    %
    if iscell(ints)
        cint = ints{ni};
    else
        cint  = ints(ni).name;
    end
    %
    fcrsc = [cint,'.rsc'];
    fcint = cint;
    roi   = sar_rsc2roi(fcrsc);
    %
    if iscell(ints)
        scale       = gmt_img2xyratio([ints{1},'.rsc']);
    else
        scale       = gmt_img2xyratio([ints(1).name,'.rsc']);
    end
    yhigh = xwid.*scale*-1;
    %
    [~,bname] = fileparts(cint);
    %
    %
    if isempty(intitle)
        mtitle = bname;%%[num2str(times(notime+1)) ' yr'];
    else
        mtitle = intitle{ni};
    end
    %
    info = sim_roirsc(fcrsc);
    [xoff,yoff,iscon,isov,gmt_snew] = gmt_sortplot(numraw,numcol,ni,xwid,yhigh);
    %
    if ni == numel(ints)
        iscon = 0;
    end
    %
    outregion = gmt_img2ps(fcint,....
        'gmt_inputformat',                gmt_inputformat,...
        'gmt_xoff',                       xoff,...
        'gmt_scale',                      gmt_scale,...
        'gmt_demgrd',                     gmt_demgrd,...
        'gmt_yoff',                       yoff,...
        'gmt_psscale_background_pen',     gmt_psscale_background_pen,...
        'gmt_psscale_background_fill',    gmt_psscale_background_fill,...
        'gmt_psscale_background_offset',  gmt_psscale_background_offset,...
        'gmt_psscale_background_offset_t',gmt_psscale_background_offset_t,...
        'gmt_psscale_background_offset_b',gmt_psscale_background_offset_b,...
        'gmt_psscale_background_offset_l',gmt_psscale_background_offset_l,...
        'gmt_psscale_background_offset_r',gmt_psscale_background_offset_r,...
        'gmt_proj',                       [' -JM',num2str(xwid),'i'],...
        'gmt_outps',                      gmt_outps,....
        'gmt_iscon',                      1,...
        'gmt_isov',                       isov,...
        'gmt_title',                      gmt_title,...
        'gmt_colorn',                     [],...
        'gmt_nanvalue',                   200,...
        'gmt_azimuth1',                   gmt_azimuth1,...
        'gmt_azimuth2',                   gmt_azimuth2,...
        'gmt_scalecof',                   gmt_scalecof,...
        'gmt_axstep',                     gmt_axstep,...
        'gmt_aystep',                     gmt_aystep,...
        'gmt_snew',                       gmt_snew,...
        'iswrap',                         iswrap,...
        'gmt_demdisplay',                 gmt_demdisplay,...
        'gmt_graddifusion',               gmt_graddifusion,...
        'gmt_gradientmethod',             gmt_gradientmethod,...
        'gmt_cptname',                    gmt_demcpt,...
        'minwrap',                        minwrap,...
        'maxwrap',                        maxwrap,...
        'gmt_minwrap',                    gmt_minwrap,...
        'gmt_maxwrap',                    gmt_maxwrap,...
        'gmt_colorbarxoffset',            '0.40i',...
        'gmt_colorbaryoffset',            '0.175i',...
        'gmt_colorbarwidth',              '0.05i',...
        'gmt_colorbarlength',             '0.6i',...
        'gmt_outdpi',                     gmt_outdpi,...
        'gmt_zinterv',                    gmt_demzinterv,...
        'gmt_unit',                       gmt_demunit,...
        'gmt_mul',                        1,...
        'gmt_lengthscale',                gmt_lengthscale,...
        'gmt_iscolorbar',                 gmt_demiscolorbar,...
        'gmt_version',                    gmt_version);
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Fault slip model
    if gmt_issarpoly==1
        inps = {'ALOS2_T047.inp','ALOS2_T048.inp','ALOS2_T157.inp',...
            'S1_Asc.inp','S1_Dec.inp','RS2_1.inp','RS2_2.inp'};
        for ninps = 1:numel(inps)
            cpoly = load(inps{ninps});
            %
            gmt_psxy4line(cpoly,...
                'outps',         gmt_outps,...
                'gmt_faultstype',' ',...)
                'isov',          1,...
                'iscon',         1,...
                'proj',          ' -J ',...
                'gmt_lwid',     '0.015c,255/255/255',...
                'linecolor',    '',...
                'mregion',      ' -R ');
            %
            p1 = cpoly(1,:);
            p2 = cpoly(4,:);
            %
            azi = sim_line2azi([p1;p2]);
            offs= [109,106,70.5,64,107,108,109];
            if ninps == 4
                printstr = ['Inf-',num2str(ninps),',8'];
            else
                printstr = ['Inf-',num2str(ninps)];
            end
            if ninps == 2
                printstr = ['Inf-',num2str(ninps),',9'];
            end
            
            gmt_pstext(...
                'text_x',        num2str(p1(1)+0.015),...
                'text_y',        num2str(p1(2)-0.125),...
                'text_string',   printstr,...
                'text_isov',     1,...
                'text_size',     '5p',...
                'text_angle',    num2str(azi-offs(ninps)),...
                'text_edgewidth','0.1',...
                'text_iscon',    1,...
                'text_fontno',   '1',...
                'text_backcolor','',...
                'text_fontcolor','white',...
                'text_pen',      text_pen,...
                'text_fillcolor','0/0/0',...
                'text_outps',    gmt_outps);
        end
    end
    %
    if isempty(gmt_oksar)==0
        %
        for nkkk = 1:numel(gmt_oksar)
            %
            gmt_inpolygons = gmt_oksar2geopolygon(gmt_oksar{nkkk},'54S',1);
            [~,~,post] = fileparts(gmt_oksar{nkkk});
            switch upper(post)
                case '.OKSAR'
                    fpara = sim_oksar2SIM(gmt_oksar{nkkk});
                otherwise
                    fpara = sim_simp2fpara(gmt_oksar{nkkk});
            end
            slip    = sqrt(fpara(:,8).^2+fpara(:,9).^2);
            maxslip = max(slip(:));
            % 
            slipcpt       = gmt_cptdb('slipmodel');
            colormapt     = gmt_importcpt(slipcpt);
            backgroundcol = fix(colormapt(2,:).*255);
            foregroundcol = fix(colormapt(end-1,:).*255);
            gmt_gmtset(...
                'gmt_color_background', [num2str(backgroundcol(1)),'/',...
                                         num2str(backgroundcol(2)),'/',...);
                                         num2str(backgroundcol(3))],...
                'gmt_color_foreground', [num2str(foregroundcol(1)),'/',...
                                         num2str(foregroundcol(2)),'/',...);
                                         num2str(foregroundcol(3))]);
            gmt_makecpt(...
                'gmt_colorn',  gmt_cptdb('slipmodel'),...
                'gmt_zstart',  0,...
                'gmt_zend',    maxslip,...
                'gmt_isreverse',1,...
                'gmt_zinterv',  maxslip./20,....
                'gmt_cptname', 'polygon_slipgeo_chk.cpt');
            gmt_psxy4polygon(gmt_inpolygons,...
                'gmt_outps',gmt_outps,...
                'gmt_transparency','30',...
                'gmt_linewide','0.08c,200/200/200 ',...
                'gmt_cptname','polygon_slipgeo_chk.cpt');
            %
            zone            = sim_oksar2utm(gmt_oksar{nkkk});
            cfpara          = fpara(slip> gmt_slipthreshold,:);
            cfpara          = sim_fparaconv(cfpara,0,3);
            index           = 1:numel(cfpara(:,10));
            cindex          = mod(index,gmt_slipselectinv);
            cfpara          = cfpara(cindex==0,:);
            [lat,lon]       = utm2deg(cfpara(:,1).*1000,cfpara(:,2).*1000,zone);
            slipdip         = cfpara(:,9).*cosd(cfpara(:,4));
            slipstr         = cfpara(:,8);
            [ewslip,snslip] = eqs_rotaxs(slipstr,slipdip,mean(cfpara(:,3)),[0,0]);
            gmt_psvelo(...
                'gmt_outps',  gmt_outps,...
                'gmt_isov',   1,...
                'gmt_iscon',  1,...
                'gmt_datainp', [lon(:),lat(:),ewslip(:),snslip(:),lon(:).*0,lon(:).*0,lon(:).*0+0.001],...
                'gmt_scale',   gmt_slipscale,....
                'gmt_lcolor',  ',0/0/0',...
                'gmt_lwid',    '0.001p',.....
                'gmt_vecpar',  '5p+a60+g250/250/250+p1.5p+e');
            %
            system(['psscale -Cpolygon_slipgeo_chk.cpt',' -D2.05i/0.25i/0.6i/0.07ih',' ',...
                '-Tp+0.03i+g220/220/220+l0.0850i+r0.0350i+t0.0250i+b0.0150i',' ',...
                '-B',gmt_slipinterval,':"":/:"Slip (m)":  -K  -O   -E  >>',...
                gmt_outps]);
            %
        end
    end
    %
    if isempty(gmt_ptdata)==0
        %
        gmt_makecpt(...
            'gmt_colorn',   gmt_inptcolortb,...
            'gmt_zstart',   gmt_ptmin,...
            'gmt_zend',     gmt_ptmax,...
            'gmt_isreverse',0,...
            'gmt_zinterv',  gmt_ptinterv,....
            'gmt_cptname',  'pt.cpt');
        %
        gmt_psxy4points(gmt_ptdata{ni},...
            'gmt_outps',    gmt_outps,...
            'gmt_proj',     ' -J ',...
            'gmt_isov',     1,...
            'gmt_iscon',    1,...
            'gmt_ptype',    'c',...
            'gmt_pcpt',     'pt.cpt',...
            'gmt_linecolor',gmt_ptlinecolor,...
            'gmt_psize',    gmt_psize,...
            'gmt_lwid',     gmt_lwid);
        system(['psscale -Cpt.cpt',' -D2.0i/0.25i/0.6i/0.07ih',' ',...
            '-Tp+0.03i+g220/220/220+l0.0850i+r0.0350i+t0.0250i+b0.0150i',' ',...
            '-B',gmt_zinterv,':"":/:"',gmt_unit,'":  -K  -O   -E  >>',...
            gmt_outps]);
    end
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %
    % Line
    %
    gmt_psxy4line(faulttopo,...
        'outps',         gmt_outps,...
        'gmt_faultstype',gmt_faultstype,...)
        'isov',          1,...
        'iscon',         1,...
        'proj',          ' -J ',...
        'gmt_lwid',      '0.035c',...
        'gmt_fillcolor', ' -G255/0/0 ',...
        'linecolor',     ',255/10/10',...
        'mregion',       ' -R ');
    if ~isempty(gmt_bound)
        gmt_psxy4line(gmt_bound,...
        'outps',         gmt_outps,...
        'gmt_faultstype',' -Sf0.25i/0.04i+l+t+o0.15i',...)
        'isov',          1,...
        'iscon',         1,...
        'proj',          ' -J ',...
        'gmt_lwid',      '0.03c',...
        'gmt_fillcolor', ' -G200/0/0 ',...
        'linecolor',     ',200/0/0',...
        'mregion',       ' -R ');
    end
    %
    gmt_psxy4line(faultpoly,...
        'outps',gmt_outps,...
        'gmt_faultstype',' ',...)
        'isov',       1,...
        'iscon',      1,...
        'proj',       ' -J ',...
        'gmt_lwid',  '0.018c,10/10/10,-.-',...
        'linecolor', '',...
        'mregion',' -R ');
    %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Location of city
    % Kathmandu, 85.300140, 27.700769
    %
    if gmt_iscapital==1
    gmt_psxy4points([85.300140, 27.700769],...
        'gmt_outps',    gmt_outps,...
        'gmt_proj',     ' -J ',...
        'gmt_isov',     1,...
        'gmt_iscon',    1,...
        'gmt_ptype',    'd',...
        'gmt_pfillc',   '0/0/0',...
        'gmt_linecolor','255/255/255',...
        'gmt_psize',    '0.25c',...
        'gmt_lwid',     '0.025c');
    %
    gmt_pstext(...
        'text_x',        num2str(85.300140-1.05),...
        'text_y',        num2str(27.700769-0.165),...
        'text_string',   'Kathmandu',...
        'text_isov',     1,...
        'text_size',     '7p',...
        'text_edgewidth','',...
        'text_iscon',    1,...
        'text_fontno',   '1',...
        'text_backcolor','',...
        'text_fontcolor','black,-=0.35p,255/255/255',...
        'text_pen',      text_pen,...
        'text_fillcolor','',...
        'gmt_outdpi',    gmt_outdpi,...
        'text_outps',    gmt_outps);
    end
    %
    % The job of plotting Kathmandu is over here
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % aftershock
    if gmt_isaftershock == 1
        %
        aftershock = 'E:\EQw\PSOInversion\Nepal_201504\data\Aftershocks_nepal_USGS.dat';
        afs        = load(aftershock);
        afs(:,3)   = afs(:,3)./45;
        gmt_psxy4points(afs,...
            'gmt_outps',    gmt_outps,...
            'gmt_proj',     ' -J ',...
            'gmt_isov',     1,...
            'gmt_iscon',    1,...
            'gmt_ptype',    'c',...
            'gmt_pfillc',   '255/0/255',...
            'gmt_linecolor','200/200/200',...
            'gmt_psize',    '',...
            'gmt_lwid',     '0.01c');
    end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Epicentral plotting section...
    %
    gmt_psxy4points(gmtepi,...
        'gmt_outps',    gmt_outps,...
        'gmt_proj',     ' -J ',...
        'gmt_isov',     1,...
        'gmt_iscon',    1,...
        'gmt_ptype',    'a',...
        'gmt_pfillc',   '255/0/0',...
        'gmt_linecolor','0/0/0',...
        'gmt_psize',    gmt_epsize,...
        'gmt_lwid',     '0.02c');
    % mountain everest
    % 27°59?17?N 86°55?31?ECoordinates: 27°59?17?N 86°55?31?E[3]
    % 86.925277777777779  27.988055555555558
    gmt_psxy4points([86.925277777777779  27.988055555555558],...
        'gmt_outps',    gmt_outps,...
        'gmt_proj',     ' -J ',...
        'gmt_isov',     1,...
        'gmt_iscon',    1,...
        'gmt_ptype',    't',...
        'gmt_pfillc',   '0/0/0',...
        'gmt_linecolor','255/255/255,solid',...
        'gmt_psize',    gmt_epsize,...
        'gmt_lwid',     '0.02c');
    gmt_pstext(...
        'text_x',        num2str(86.925277777777779+0.05),...
        'text_y',        num2str(27.988055555555558+0.05),...
        'text_string',   'Mountain Everest',...
        'text_isov',     1,...
        'text_size',     '6.5p',...
        'text_edgewidth','',...
        'text_iscon',    1,...
        'text_fontno',   '1',...
        'text_backcolor','',...
        'text_fontcolor','black,-=0.35p,255/255/255',...
        'text_pen',      text_pen,...
        'text_fillcolor','',...
        'gmt_outdpi',    gmt_outdpi,...
        'text_outps',    gmt_outps);
    % Epicentral station plotting over
    %
    if gmt_isisoseismal == 1
        %
        file1 = 'E:\EQw\PSOInversion\Nepal_201504\data\1988_source.dat';
        file2 = 'E:\EQw\PSOInversion\Nepal_201504\data\1992_source.dat';
        isoseis = load(file1);
        %
        gmt_psxy4line(isoseis,...
            'outps',gmt_outps,...
            'gmt_faultstype',' ',...)
            'isov',       1,...
            'iscon',      1,...
            'proj',       ' -J ',...
            'gmt_lwid',  '0.01c,255/0/0,---',...
            'linecolor', '',...
            'mregion',' -R ');
%         isoseis = load(file2);
%         gmt_psxy4line(isoseis,...
%             'outps',gmt_outps,...
%             'gmt_faultstype',' ',...)
%             'isov',       1,...
%             'iscon',      1,...
%             'proj',       ' -J ',...
%             'gmt_lwid',   '0.035c,255/0/0,solid',...
%             'linecolor',  '',...
%             'mregion',    ' -R ');
        %
        histeq = 'E:\EQw\PSOInversion\Nepal_201504\data\historicEQ_source.dat';
        eqdata = load(histeq);
        gmt_psxy4points(eqdata,...
            'gmt_outps',    gmt_outps,...
            'gmt_proj',     ' -J ',...
            'gmt_isov',     1,...
            'gmt_iscon',    1,...
            'gmt_ptype',    'a',...
            'gmt_pfillc',   '',...
            'gmt_linecolor','0/0/0',...
            'gmt_psize',    gmt_epsize,...
            'gmt_lwid',     '0.65c');
        histeqstr = {'1934','1833'};
        for neq = 1:numel(eqdata(:,1))
            gmt_pstext(...
                'text_x',        num2str(eqdata(neq,1)+0.075),...
                'text_y',        num2str(eqdata(neq,2)+0.05),...
                'text_string',   histeqstr{neq},...
                'text_isov',     1,...
                'text_size',     '7p',...
                'text_edgewidth','',...
                'text_iscon',    1,...
                'text_fontno',   '6',...
                'text_backcolor','',...
                'text_fontcolor','200/0/0',...
                'text_pen',      text_pen,...
                'text_fillcolor','',...
                'gmt_outdpi',    gmt_outdpi,...
                'text_outps',    gmt_outps);
        end
    end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % GPS velocity
    if gmt_isgps == 1
        gmt_gps = read_nepalGPS();
        %
        % Stations
        loc = gmt_gps.loc;
        gmt_psxy4points(loc(:,[2,1]),...
            'gmt_outps',    gmt_outps,...
            'gmt_proj',     ' -J ',...
            'gmt_isov',     1,...
            'gmt_iscon',    1,...
            'gmt_ptype',    'i',...
            'gmt_pfillc',   '20/20/200',...
            'gmt_linecolor','0/0/0',...
            'gmt_psize',    gmt_gpspsize,...
            'gmt_lwid',     '0.005c');
        % Station names
        stations = gmt_gps.stations;
        %
        for nk = 1:numel(loc(:,1))
            gmt_pstext(...
                'text_x',        num2str(loc(nk,2)+0.05),...
                'text_y',        num2str(loc(nk,1)-0.085),...
                'text_string',   stations{nk},...
                'text_isov',     1,...
                'text_size',     '4.5p',...
                'text_edgewidth','',...
                'text_iscon',    1,...
                'text_fontno',   '5',...
                'text_backcolor','',...
                'text_fontcolor',gmt_gpsfontcolor,...
                'text_pen',      text_pen,...
                'text_fillcolor','',...
                'gmt_outdpi',    gmt_outdpi,...
                'text_outps',    gmt_outps);
        end
        %
        % GPS Horizontal component
        enu         = gmt_gps.enu./100;
        err         = gmt_gps.err;
        index       = abs(enu(:,2)) > 1;
        gps_horizon = [loc(:,2),  loc(:,1),...
            enu(:,1:2),err(:,1:2),...
            err(:,1).*0+0.001];
        %
        gmt_psvelo(...
            'gmt_outps',   gmt_outps,...
            'gmt_isov',    1,...
            'gmt_iscon',   1,...
            'gmt_datainp', gps_horizon,...
            'gmt_scale',   '0.5',....
            'gmt_lcolor',  ',20/20/200',...
            'gmt_lwid',    gmt_gpsvellwid,...
            'gmt_vecattr', gmt_gpsvelvecattr,...
            'gmt_vecpar',  '5p+a60+g20/20/200+p2.0p+e');
        %
        % GPS Vertical deformation
        gps_horizon = [loc(:,2),  loc(:,1),...
            enu(:,3).*0,enu(:,3),err(:,1:2).*0,...
            err(:,1).*0+0.001];
        gmt_psvelo(...
            'gmt_outps',  gmt_outps,...
            'gmt_isov',   1,...
            'gmt_iscon',  1,...
            'gmt_datainp', gps_horizon,...
            'gmt_scale',   '0.5',....
            'gmt_lcolor',  ',20/20/200',...
            'gmt_lwid',    gmt_gpsvellwid,...
            'gmt_vecattr', gmt_gpsvelvecattr,...
            'gmt_vecpar',  '8p+a60+g20/20/200+p2.0p+e');
        
        %         Check InSAR-based slip model...
        %         A joint slip model with InSAR and GPS together...
        %         GPS_InSAR_18degree_dist.oksar
        %         oksarfile = 'E:\EQw\PSOInversion\Nepal_201504\oksar\GPS_InSAR_18degree_dist.oksar';
        % %ALOS2_GPS_VariousDips_20degree_dist.oksar';
        % oksarfile = 'E:\EQw\PSOInversion\Nepal_201504\oksar\GPS_InSAR_18degree_dist.oksar';%
        oksarfile = 'E:\EQw\PSOInversion\Nepal_201504\oksar\ALOS2_VariousDips_18degree_dist.oksar';
        fpara     = sim_oksar2SIM(oksarfile);
        zone      = sim_oksar2utm(oksarfile);
        [x,y]     = ll2utm(loc(index==1,1),loc(index==1,2),zone);
        x         = x./1000; 
        y         = y./1000;
        dis       = multiokadaALP(fpara,x,y);
        simgps    = [loc(index==1,2),loc(index==1,1),dis.E,dis.N,dis.E.*0, dis.E.*0,dis.E.*0];
        %
        gmt_psvelo(...
            'gmt_outps',  gmt_outps,...
            'gmt_isov',   1,...
            'gmt_iscon',  1,...
            'gmt_datainp', simgps,...
            'gmt_scale',   '0.5',....
            'gmt_lcolor',  ',155/0/0',...
            'gmt_lwid',    '0.1p',...
            'gmt_vecattr', gmt_gpsvelvecattr,...
            'gmt_vecpar',  '5p+a60+g155/0/0+p1.5p+e');
        %
        % Simulated vertical deformation...
        %
        simgps = [loc(index==1,2),loc(index==1,1),dis.E.*0,dis.V,dis.E.*0, dis.E.*0,dis.E.*0];
        %
        gmt_psvelo(...
            'gmt_outps',  gmt_outps,...
            'gmt_isov',   1,...
            'gmt_iscon',  1,...
            'gmt_datainp', simgps,...
            'gmt_scale',   '0.5',....
            'gmt_lcolor',  ',155/0/0',...
            'gmt_lwid',    gmt_gpsvellwid,...
            'gmt_vecattr', gmt_gpsvelvecattr,...
            'gmt_vecpar',  '3p+a60+g155/0/0+p1.0p+e');
        %
        % GPS scale bar, for observations
        reflat  = 25.65;
        reflon  = 87;
        yoffset = 0.175;
        simgps = [reflon,reflat,3,0,0,0,0];
        %
        gmt_psvelo(...
            'gmt_outps',  gmt_outps,...
            'gmt_isov',   1,...
            'gmt_iscon',  1,...
            'gmt_datainp', simgps,...
            'gmt_scale',   '0.5',....
            'gmt_lcolor',  ',20/20/200',...
            'gmt_lwid',    gmt_gpsvellwid,...
            'gmt_vecattr', gmt_gpsvelvecattr,...
            'gmt_vecpar',  '5p+a60+g20/20/200+p1.1p+e');
        
        gmt_pstext(...
            'text_x',        num2str(reflon),...
            'text_y',        num2str(reflat+yoffset*1-0.075),...
            'text_string',   'OBS GPS (3m)',...
            'text_isov',     1,...
            'text_size',     '4.25p',...
            'text_edgewidth','',...
            'text_iscon',    1,...
            'text_fontno',   '5',...
            'text_backcolor','',...
            'text_fontcolor',gmt_gpsfontcolor,...
            'text_pen',      text_pen,...
            'text_fillcolor','',...
            'gmt_outdpi',    gmt_outdpi,...
            'text_outps',    gmt_outps);
        %
        % for simulation
        simgps = [reflon,reflat+yoffset*2,3,0,0,0,0];
        %
        gmt_psvelo(...
            'gmt_outps',   gmt_outps,...
            'gmt_isov',    1,...
            'gmt_iscon',   1,...
            'gmt_datainp', simgps,...
            'gmt_scale',   '0.5',....
            'gmt_lcolor',  ',155/0/0',...
            'gmt_lwid',    gmt_gpsvellwid,...
            'gmt_vecattr', gmt_gpsvelvecattr,...
            'gmt_vecpar',  '5p+a60+g155/0/0+p1.1p+e');
        %
        gmt_pstext(...
            'text_x',         num2str(reflon),...
            'text_y',         num2str(reflat+yoffset*3-0.075),...
            'text_string',    'Simulation (3m)',...
            'text_isov',      1,...
            'text_size',      '4.25p',...
            'text_edgewidth', '',...
            'text_iscon',     1,...
            'text_fontno',    '5',...
            'text_backcolor', '',...
            'text_fontcolor', gmt_gpsfontcolor,...
            'text_pen',       text_pen,...
            'text_fillcolor', '',...
            'gmt_outdpi',     gmt_outdpi,...
            'text_outps',     gmt_outps);
    end
    %
    % GPS field over
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Convergence rate
    gps_horizon = [86.5,26.01,0.35,1, 0, 0, 0.001];
    gmt_psvelo(...
        'gmt_outps',  gmt_outps,...
        'gmt_isov',   1,...
        'gmt_iscon',  1,...
        'gmt_datainp', gps_horizon,...
        'gmt_scale',   '0.5',....
        'gmt_lcolor',  ',255/255/255',...
        'gmt_lwid',    gmt_gpsvellwid,...
        'gmt_vecattr', gmt_gpsvelvecattr,...
        'gmt_vecpar',  '8p+a70+g255/255/255+p4.5p+e');
     gmt_pstext(...
        'text_x',        num2str(85.92),...
        'text_y',        num2str(25.75),...
        'text_string',   '~36.3 mm/yr',...
        'text_angle',    '0',...
        'text_isov',     1,...
        'text_size',     '7p',...
        'text_fontno',   '1',...
        'text_edgewidth','',...
        'text_iscon',    1,...
        'text_backcolor','',...
        'text_fontcolor','255/255/255',...
        'text_fillcolor','',...
        'text_outps',    gmt_outps);
    %
    
    %
    %
    if gmt_isglobal==1
        gmt_iscon = 1;
    else
        gmt_iscon = gmt_superiscon;
    end
    %
    gmt_pstext(...
        'text_x',        num2str(outregion(1)+(outregion(2)-outregion(1))*0.0175),...
        'text_y',        num2str(outregion(4)-(outregion(4)-outregion(3))*0.05),...
        'text_string',   mtitle,...
        'text_isov',     1,...
        'text_size',     text_size,...
        'text_edgewidth','',...
        'text_iscon',    gmt_iscon,...
        'text_backcolor','',...
        'text_fontcolor',text_fontcolor,...
        'text_pen',      text_pen,...
        'text_fillcolor','',...
        'gmt_outdpi',    gmt_outdpi,...
        'text_outps',    gmt_outps,...
        'gmt_version',   gmt_version);
    %
    if islegend == 1
        %
        scale = 0.12;
        polyinput = [roi(1)+0.7*(roi(2)-roi(1)),roi(3)+scale*(roi(4)-roi(3));...
                     roi(1)+0.7*(roi(2)-roi(1)),roi(3);...
                     roi(2)                     ,roi(3);...
                     roi(2)                     ,roi(3)+scale*(roi(4)-roi(3));...
                     roi(1)+0.7*(roi(2)-roi(1)),roi(3)+scale*(roi(4)-roi(3))];
        gmt_psxy4polygon(polyinput,...
            'gmt_fillcolor','200/200/200',...
            'gmt_zvalue',   '0.8',...
            'gmt_outps',    gmt_outps);
        %
        lafs = [roi(1)+0.7*(roi(2)-roi(1))+0.05, roi(3) + 0.15, 4;
                roi(1)+0.7*(roi(2)-roi(1))+0.45,      roi(3) + 0.15, 5;
                roi(1)+0.7*(roi(2)-roi(1))+0.85,     roi(3) + 0.15, 6;...
                roi(1)+0.7*(roi(2)-roi(1))+1.25,     roi(3) + 0.15, 7];
        %
        ctitle = {'M4','M5','M6','M7'};
        %
        for nlfeq = 1:4
            %
            lafs(nlfeq,3)   = lafs(nlfeq,3)./45;
            gmt_psxy4points(lafs(nlfeq,:),...
                'gmt_outps',    gmt_outps,...
                'gmt_proj',     ' -J ',...
                'gmt_isov',     1,...
                'gmt_iscon',    1,...
                'gmt_ptype',    'c',...
                'gmt_pfillc',   '255/0/255',...
                'gmt_linecolor','200/200/200',...
                'gmt_psize',    '',...
                'gmt_lwid',     '0.01c');
            gmt_pstext(...
                'text_x',        num2str(lafs(nlfeq,1)+0.05),...
                'text_y',        num2str(lafs(nlfeq,2)-0.0),...
                'text_string',   ctitle{nlfeq},...
                'text_isov',     1,...
                'text_fontno',   '7',...
                'text_size',     '5.85p',...
                'text_edgewidth','',...
                'text_iscon',    1,...
                'text_backcolor','',...
                'text_fontcolor','0/0/0',...
                'text_fillcolor','',...
                'gmt_outdpi',    gmt_outdpi,...
                'text_outps',    gmt_outps);
        end
        %
        %
        gmt_pstext(...
                'text_x',         num2str(polyinput(1,1)+0.50),...
                'text_y',         num2str(max(polyinput(:,2)) - 0.13 ),...
                'text_string',    'Aftershocks',...
                'text_isov',      1,...
                'text_fontno',    '7',...
                'text_size',      '6.25p',...
                'text_edgewidth', '',...
                'text_iscon',     1,...
                'text_backcolor', '',...
                'text_fontcolor', '0/0/0',...
                'text_fillcolor', '',...
                'gmt_outdpi',     gmt_outdpi,...
                'text_outps',     gmt_outps);
    end
    %
    if gmt_isglobal == 1
        %
        gmt_global(roi,...
            'gmt_xoff',    gmt_globalxoff,...
            'gmt_yoff',    gmt_globalyoff,...
            'gmt_mapsize', gmt_globalmapsize,...
            'gmt_iscon',   gmt_superiscon,...
            'gmt_isov',    1,...
            'gmt_type',    gmt_globaltype,...
            'gmt_outps',   gmt_outps);
    end
    %if  iscon == 0
    %    return;
    %end
end
%