function gmt_plotprofile(x,y,stitle,etitle,gmt_outps,varargin)
% 
%
% linecolor,psize,fontsize,lwid,bufferwidth,gmt_fontcolor)
%
% Developed by FWP, @IGPP of SIO, UCSD, 2013-11-18
%
linecolor     = ',255/255/255';
psize         = '2.5p';
fontsize      = '10';
lwid          = '0.02c';
shiftdist     = 1.0;
bufferwidth   = 0;
gmt_fontcolor = '0/0/0';
gmt_iscon     = 1;
%
for ni = 1:2:numel(varargin)
    par = varargin{ni};
    val = varargin{ni+1};
    eval([par,'=val;']);
end
%
x = x(1:2);
y = y(1:2);
gmt_psxy4line([x(:),y(:)],...
    'outps',gmt_outps,...
    'gmt_faultstype','',...)
    'isov', 1,...
    'iscon',1,...
    'proj',' -J ',...
    'gmt_fillcolor',' -G255/255/255',...
    'gmt_lwid', lwid,...
    'linecolor',linecolor,...
    'mregion',' -R ');
gmt_psxy4points([x(1),y(1)],...
    'gmt_outps',gmt_outps,...
    'gmt_faultstype','',...)
    'gmt_isov', 1,...
    'gmt_iscon',1,...
    'gmt_proj',' -J ',...
    'gmt_lwid','0.0003c',...
    'gmt_psize',psize,...
    'gmt_ptype','c',...
    'gmt_pfillc','255/255/255',...
    'gmt_linecolor',linecolor,...
    'gmt_mregion',' -R ');
gmt_psxy4points([x(2),y(2)],...
    'gmt_outps',gmt_outps,...
    'gmt_faultstype','',...)
    'gmt_isov', 1,...
    'gmt_iscon',1,...
    'gmt_proj',' -J ',...
    'gmt_lwid','0.0003c',...
    'gmt_psize',psize,...
    'gmt_ptype','c',...
    'gmt_pfillc','255/255/255',...
    'gmt_linecolor',linecolor,...
    'gmt_mregion',' -R ');
%
[~,sindex]  = sort(y(:));
azi         = sim_line2azi([x(:),y(:)]);
[xlon,ylat] = sim_pointshift(x(sindex(1)),y(sindex(1)),azi,'right',shiftdist*3);
%
gmt_pstext('text_x',num2str(xlon),...
    'text_y',num2str(ylat),...
    'text_size',fontsize,...
    'text_angle',num2str(270-azi),...
    'text_string',stitle,...
    'text_outps',gmt_outps,...
    'text_backcolor','',...
    'text_iscon',1,...
    'text_edgecolor','',...
    'text_fontno','1',....
    'text_fontcolor',gmt_fontcolor,...
    'text_edgewidth','');
%
[xlon,ylat] = sim_pointshift(x(sindex(2)),y(sindex(2)),azi,'left',shiftdist*1.25);
%
if bufferwidth == 0
    ciscon = gmt_iscon;
else
    ciscon = 1;
end
%
%
gmt_pstext('text_x',num2str(xlon),...
    'text_y',       num2str(ylat),...
    'text_size',    fontsize,...
    'text_fontno',  '1',....
    'text_angle',   num2str(270-azi),...
    'text_string',  etitle,...
    'text_outps',   gmt_outps,...
    'text_backcolor','',...
    'text_iscon',   ciscon,...
    'text_edgecolor','0/0/0',...
    'text_fontcolor',gmt_fontcolor,...
    'text_edgewidth','');
%
if bufferwidth > 0
    [x,y] = sim_profile2buffer(x(1:2),y(1:2),bufferwidth);
    gmt_psxy4line([x(:),y(:)],...
        'outps',gmt_outps,...
        'gmt_faultstype','',...)
        'isov',1,...
        'iscon',gmt_iscon,...
        'proj',' -J ',...
        'gmt_fillcolor','',...
        'gmt_lwid','0.02c',...
        'gmt_linestyle',',---',...
        'linecolor',linecolor,...
        'mregion',' -R ');
end