function [outregion,gmt_outproj,gmt_outmregion] = gmt_oksar2slip_v2(oksars,figlable,usgslocs,gmt_outps,varargin)
%
% Developed by FWP, @UoG, 2014-11-02
% A bug was pointed out by Dr. Yongsheng Li, @ BJ, 2015-08-22 on line 245
% 
%
if nargin < 4
   disp('outregion = gmt_oksar2slip_v2(oksars,figlable,usgslocs,gmt_outps,varargin)');
   return
end
%    
gmt_usgsfsize       = '5p';
gmt_usgslocx        = 3;
gmt_usgslocy        = 0.5;
gmt_grdmregion      = [];
gmt_orientation     = 0;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% slip vector
gmt_slipvecpar      = '5p+a50+g155/155/155+p1.5p+e';
gmt_slipvectorscale = '0.25';
gmt_slipvectorlwid  = '0.1p';
gmt_velsamp         = 3;
gmt_velthresh       = 0.1;
gmt_orienx          = 0;
gmt_orieny          = 0;
gmt_offsetsetstrike = 1;
%
gmt_cptinv          = [];
gmt_ytitle          = 'Length(km)';
gmt_axstep          = '5';
gmt_aystep          = '5';
gmt_oksar2grdcor    = 'xy'; 
gmt_textyshift      = 0.09;
gmt_plotbsnew       = 'SnEw';
gmt_labelb          = '(b)';
gmt_lablesize       = '6';
gmt_colorbarxoff    = '0.35i';
gmt_isov            = 0;
gmt_iscon           = 0;
gmt_eqmag           = [];
gmt_xoff            = '2i';
gmt_yoff            = '2i';
gmt_isvel           = 1;
gmt_bxtitle         = 'Accumulated Moment along Strike (10@+17@+@::N.m)';
gmt_isbplot         = 0;
gmt_iscontour       = 0;
gmt_conwid          = '0.05p';
gmt_topunit         = '(m)';
gmt_slipmodel       = 'syn';
gmt_istop           = 1;
gmt_slipmin         = 0;
gmt_slipmax         = 2;
gmt_outregion       = [];
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% slip contour
gmt_labelinterv     = '0.5';
gmt_sliplow         = [];
gmt_sliphigh        = [];
gmt_slipinterv      = [];
gmt_labelsize       = '5p,white,-=0.2p,black';
gmt_concolor        = ',100/100/100';
gmt_constart        = 0.1;
gmt_conend          = 10;
gmt_coninv          = 0.1;
gmt_cptname         = [];
gmt_width           = '2i';
gmt_height          = '0.8i';
gmt_topsnew         = 'SnWe';
gmt_mregion         = [];
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for ni = 1:2:numel(varargin)
    par = varargin{ni};
    val = varargin{ni+1};
    eval([par,'=val;']);
end
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[~,~,postfix] = fileparts(oksars);
%
if strcmpi(postfix,'.simp')
    [~,zone] = sim_simp2fpara(oksars);
else
    zone = sim_oksar2utm(oksars);
end
%
[eqx,eqy] = deg2utm(usgslocs(1,2),usgslocs(1,1),zone);
%
outgrd = '2003.grd';
outroi = '2003.ImG';
%
if isempty(gmt_grdmregion)
    gmt_grdmregion = gmt_mregion;
end
%
gmt_oksar2grd(oksars,'2003.grd',0,gmt_slipmodel,gmt_oksar2grdcor,...
    'refxy',[eqx,eqy]./1000,...
    'gmt_mregion',gmt_grdmregion);
%
flag = 0;
if isempty(gmt_cptname)
    gmt_cptname  = gmt_cptdb('slip');
    flag = 1;
end
%
if exist(gmt_cptname,'file')
    colormapt     = gmt_importcpt(gmt_cptname);
else
    colormapt = [];
end
if ~isnan(colormapt)
    %
    if flag==0
        foregroundcol = fix(colormapt(2,:).*255);
        backgroundcol = fix(colormapt(end-1,:).*255);
    else
        backgroundcol = fix(colormapt(2,:).*255);
        foregroundcol = fix(colormapt(end-1,:).*255);
    end
    backcol = [num2str(backgroundcol(1)),'/',...
        num2str(backgroundcol(2)),'/',...
        num2str(backgroundcol(3))];
    %
    forecol = [num2str(foregroundcol(1)),'/',...
        num2str(foregroundcol(2)),'/',...
        num2str(foregroundcol(3))];
else
    backcol = '0/0/0';
    forecol = '255/255/255';
end
%
%
if gmt_istop == 1
    gmt_gmtset('gmt_color_nan',       '255/255/255',...
        'gmt_paper_media',            'A0',...
        'gmt_annot_font_size_primary','5p',...
        'gmt_tick_length',            '0.02c',...
        'gmt_color_background',       forecol,...
        'gmt_label_font_size',        '5p',...
        'gmt_color_foreground',       backcol,...
        'gmt_tick_pen',               '0.05p',...
        'gmt_annot_offset_primary',   '0.025c',...
        'gmt_label_offset',           '0.1c',...
        'gmt_oblique_annotation',     '2' ,...
        'gmt_frame_pen',              '0.02c',...
        'gmt_frame_width',            '0.00001c');
    %
    gmt_grd2roi(outgrd,outroi,'f');
    gmt_makecpt(...
        'gmt_colorn',   gmt_cptname,...
        'gmt_cptname',  'Img.cpt',...
        'gmt_logrithm', '  ',...
        'gmt_zstart',   gmt_slipmin,...
        'gmt_isreverse',1,...
        'gmt_zend',     gmt_slipmax,...
        'gmt_zinterv',  0.01,...
        'gmt_iscontin', 1);
    %
    if isempty(gmt_cptinv)
       gmt_cptinv = abs(gmt_slipmax);
    end
    %
    [outregion,gmt_outproj,gmt_outmregion] = gmt_img2ps(outroi,....
        'gmt_mregion', gmt_mregion,...
        'gmt_demgrd',  [],...
        'gmt_xoff',    gmt_xoff,...
        'gmt_yoff',    gmt_yoff,...
        'gmt_proj',    [' -JX',gmt_width,'/-',gmt_height,' '],...
        'gmt_outps',   gmt_outps,....
        'gmt_iscon',   1,...
        'gmt_isov',    gmt_isov,...
        'gmt_colorn',  'Img.cpt',...
        'gmt_nanvalue',0,...
        'gmt_axstep',  gmt_axstep,...
        'gmt_aystep',  gmt_aystep,...
        'gmt_snew',    gmt_topsnew,...
        'gmt_xtitle',  gmt_ytitle,...
        'gmt_ytitle',  'Depth (km)',...
        'iswrap',      0,...
        'gmt_cptname', [],...
        'minwrap',     gmt_slipmin,...
        'maxwrap',     gmt_slipmax,...
        'gmt_minwrap', gmt_slipmin,...
        'gmt_maxwrap', gmt_slipmax,...
        'gmt_colorbarxoffset', gmt_colorbarxoff,...'0.35i',...
        'gmt_colorbaryoffset', '0.135i',...
        'gmt_colorbarwidth',   '0.04i',...
        'gmt_colorbarlength',  '0.5i',...
        'gmt_zinterv',         gmt_cptinv,...
        'gmt_unit',            gmt_topunit,...
        'gmt_mul',             1);
    gmt_psxy4points([0,usgslocs(3)],...
        'gmt_outps',  gmt_outps,...
        'gmt_mregion',' -R ',...
        'gmt_proj',   ' -J ',...
        'gmt_pfillc', '255/0/0 ',...
        'gmt_ptype',  'a',...
        'gmt_psize',  '0.18c',...
        'gmt_isov',   1,...
        'gmt_iscon',  1);
    gmt_pstext(...
        'text_x',     num2str(gmt_usgslocx),...
        'text_y',     num2str(usgslocs(3)+gmt_usgslocy),...
        'text_string','USGS',...
        'text_size',  gmt_usgsfsize,...
        'text_isov',  1,...
        'text_iscon', 1,...
        'text_outps', gmt_outps);
else
    outregion = gmt_outregion;
end
%
%
if gmt_isvel == 1
    
    %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % velocity arrow
    if strcmpi(postfix,'.oksar')
        fpara = sim_oksar2SIM(oksars);
    else
        fpara = sim_simp2fpara(oksars);
    end
    %
    strike = mean(fpara(:,3));
    [x,y]  = eqs_rotaxs(fpara(:,1),fpara(:,2),strike,[eqx,eqy]./1000);
    %
    switch upper(gmt_oksar2grdcor)
        case 'XY'
            inpx = x;
            %refc = x;
        case 'X'
            inpx = x;
            %refc = x;
        case 'Y'
            inpx = y;
            %refc = y;
    end
    arrs = [inpx,fpara(:,5),fpara(:,8),fpara(:,9).*-1,...
            inpx.*0+0.00001,inpx.*0+0.00001,...
            inpx.*0+0.00001];
    cni  = [];
    %
    % A bug was found by Yongsheng, @ Bj, 2015-08-22
    % line 245 has been changed to line 246
    % slip      = sqrt(arrs(:,3).^2+arrs(:,4).^4);
    slip      = sqrt(arrs(:,3).^2+arrs(:,4).^2);
    [~,index] = sort(slip,'descend');
    %
    for ni = 1:gmt_velsamp:numel(index)
        cni = [cni;index(ni)];
    end
    arrs = arrs(cni,:);
    slip = sqrt(arrs(:,3).^2+arrs(:,4).^2);
    arrs = arrs(slip>=gmt_velthresh,:);
    %
    gmt_psvelo(...
        'gmt_outps',   gmt_outps,...
        'gmt_isov',    1,...
        'gmt_iscon',   1,...
        'gmt_datainp', arrs,...
        'gmt_scale',   gmt_slipvectorscale,....
        'gmt_lcolor',  ',155/155/155',...
        'gmt_lwid',    gmt_slipvectorlwid,...
        'gmt_vecpar',  gmt_slipvecpar);
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %
end
%
if gmt_iscontour == 1
    gmt_cptname = 'moment_countour.cpt';
    %
    gmt_makecpt('gmt_colorn','gray',...
        'gmt_cptname',gmt_cptname,'gmt_logrithm','  ',...
        'gmt_zstart', gmt_constart,...
        'gmt_zend',   gmt_conend,...
        'gmt_zinterv',gmt_coninv,...
        'gmt_iscontin',1);
    %
    gmt_grdcontour(outgrd,...
        'gmt_isov',       1,...
        'gmt_sliplow',    gmt_sliplow,...
        'gmt_sliphigh',   gmt_sliphigh,...
        'gmt_slipinterv', gmt_slipinterv,...
        'gmt_cptname',    gmt_cptname,...
        'gmt_concol',     gmt_concolor,... 
        'gmt_labelinterv',gmt_labelinterv,...
        'gmt_conlw',      gmt_conwid,...
        'gmt_labelsize',  gmt_labelsize,...
        'gmt_iscon',      1,...
        'gmt_lables',     '4p',...
        'gmt_outps',  gmt_outps);
end
%
if gmt_orientation == 1
   orient_fault = [gmt_orienx,...
                   gmt_orieny,...
                   2,0,0,0,0.01];
   %
   gmt_psvelo(...
       'gmt_outps',   gmt_outps,...
       'gmt_isov',    1,...
       'gmt_iscon',   1,...
       'gmt_datainp', orient_fault,...
       'gmt_scale',   '0.5',....
       'gmt_lcolor',  ',100/0/0',...
       'gmt_vecpar',  '5p+a60+g100/0/0+p1.0p+e+l');
   %
   strike = mean(fpara(:,3));
   dip    = mean(fpara(:,4));
   [~,mrake] = sim_calrake(fpara,1);
   %
   gmt_pstext(...
        'text_x',         num2str(gmt_orienx),...
        'text_y',         num2str(gmt_orieny-gmt_offsetsetstrike),...
        'text_string',    ['Str:', num2str(strike,'%4.1f'),'@+o@+@:: Dip:',num2str(dip,'%3.1f'),'@+o@+@::'],...
        'text_isov',      1,...
        'text_fontno',    '7',...
        'text_size',      '5p',...
        'text_edgewidth', '',...
        'text_iscon',     1,...
        'text_backcolor', '',...
        'text_fillcolor', '',...
        'text_outps',     gmt_outps);
    gmt_pstext(...
        'text_x',         num2str(gmt_orienx),...
        'text_y',         num2str(gmt_orieny+gmt_offsetsetstrike.*1.45),...
        'text_string',    ['Mean Rake:',num2str(mrake,'%3.1f'),'@+o@+@::'],...
        'text_isov',      1,...
        'text_fontno',    '7',...
        'text_size',      '5p',...
        'text_edgewidth', '',...
        'text_iscon',     1,...
        'text_backcolor', '',...
        'text_fillcolor', '',...
        'text_outps',     gmt_outps);
end

if gmt_isbplot == 1
    text_iscon = 1;
else
    text_iscon = gmt_iscon;
end
if gmt_istop == 1
    %
    gmt_pstext(...
        'text_x',     num2str(outregion(1)+0.005*(outregion(2)-outregion(1))),...
        'text_y',     num2str(outregion(3)+gmt_textyshift*(outregion(4)-outregion(3))),...
        'text_string',figlable,...
        'text_size',  '6',...
        'text_isov',  1,...
        'text_iscon', text_iscon,...
        'text_outps', gmt_outps);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if gmt_isbplot == 1
    [data,~,y,info] = sim_defreadroi(outroi,'float',1,0);
    s    = abs(info.x_step.*info.y_step)*10^6; % m^2
    mu   = 3.23e10;
    data = data.*mu.*s;
    mo   = sum(data')./10^17;
    deps = y(:,1)';%linspace(info.y_first,info.y_step*numel(mo)+info.y_first,numel(mo));
    %
    mo   = [0,mo,0,0];
    deps = [deps(1),deps,deps(end),deps(1)];
    %
    gmt_psxy4polygon([mo',deps'],...
        'gmt_proj',    [' -JX',gmt_height,'/-',gmt_height,''],...0.8i',...
        'gmt_mregion', [' -R',num2str(min(mo)),'/',num2str(max(mo)),'/',...
                        num2str(outregion(3)),'/',num2str(outregion(4))],...
        'gmt_isov',  1,....
        'gmt_iscon', 1,...
        'gmt_xoff',  gmt_width,...
        'gmt_yoff',  '0i',...
        'gmt_snew',  gmt_plotbsnew,...
        'gmt_xtitle', gmt_bxtitle,...
        'gmt_ytitle', 'Depth (km)',...
        'gmt_axoff', '0.5',...
        'gmt_ayoff', '5',...
        'gmt_outps',  gmt_outps);%varargin
    %
    
    if isempty(gmt_eqmag)
        gmt_eqmag = 2/3*log10(sum(mo).*10^17)-6.0333;
    end
    %
    gmt_pstext(...
        'text_x',         num2str(min(mo)+0.425*(max(mo)-min(mo))),...
        'text_y',         num2str(outregion(3)+gmt_textyshift*(outregion(4)-outregion(3))),...
        'text_string',['Mw ',num2str(gmt_eqmag,'%3.2f')],...
        'text_size',  gmt_lablesize,...
        'text_isov',  1,...
        'text_iscon', 1,...
        'text_outps', gmt_outps);
    %
    gmt_pstext(...
        'text_x',         num2str(min(mo)+0.01*(max(mo)-min(mo))),...
        'text_y',     num2str(outregion(3)+gmt_textyshift*(outregion(4)-outregion(3))),...
        'text_string',gmt_labelb,...
        'text_size',  gmt_lablesize,...
        'text_isov',  1,...
        'text_iscon', gmt_iscon,...
        'text_outps', gmt_outps);
end