function gmt_batchoptimaldipalpha(inmat,outname,gmt_xsize,gmt_ysize,thresh)
%
% gmt plot
% Created by FWP,@ GU, 2012-10-11
%
%
if nargin < 1
    disp('gmt_batchoptimaldipalpha(inmat,outname,gmt_xsize,gmt_ysize,thresh)');
    return
end
%
if nargin < 3
    gmt_xsize = 3;
end
%
if nargin < 4
    gmt_ysize = 0.5;
end
if nargin < 5
    thresh = [];
end
%
gmt_proj  = ' -JX3i/2.4i ';
gmt_iscolorbar = 0;
%outname   = 'bm_2011v2.opt';
%inmat     = 'SMESTv3.1.mat';
text_size = 12;
%
outabic = sim_optimaldipalpha(inmat,outname,thresh);
%
%
index   = find(outabic(:,3) == min(outabic(:,3)));
%
dip     = outabic(index(1),1);
valpha  = outabic(outabic(:,1)==dip,:);
alpha   = valpha(:,2);
%
vstd    = (valpha(:,4)-min(valpha(:,4)))./(max(valpha(:,4))-min(valpha(:,4)));
vroug   = (valpha(:,5)-min(valpha(:,5)))./(max(valpha(:,5))-min(valpha(:,5)));
vfun    = valpha(:,3);
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%(valpha(:,3)-min(valpha(:,3)))./(max(valpha(:,3))-min(valpha(:,3)));
%
%
gmt_gmtset(...
    'gmt_paper_media','A0',...
    'gmt_color_foreground','255/255/255',...
    'gmt_color_background','0/0/0',...
    'gmt_annot_font_size_primary','8p',...
    'gmt_basemap_type','plain',...
    'gmt_frame_width','0.03c',...
    'gmt_frame_pen','1p',...
    'gmt_label_font_size','10p',...
    'gmt_label_offset','0.04c',...
    'gmt_tick_length','0.04c',...
    'gmt_annot_min_spacing','0.001c');
gmt_psxy4line([alpha,vstd],...
    'outps',[outname,'.ps'],...
    'gmt_lwid','0.06c',...
    'linecolor',',50/50/50',...
    'xoff','1i',...
    'yoff','1i',...
    'isov',0,...
    'iscon',1,...
    'xstep','3f3',...
    'ystep','0.1',...
    'snew','SnW',...
    'xtitle','@~a@+2',... 
    'linestyle',',--',...
    'ytitle','@~x  &  y@ ',... 
    'proj',gmt_proj);
%
gmt_psxy4line([alpha,vroug],...
    'outps',[outname,'.ps'],...
    'gmt_lwid','0.06c',...
    'linecolor',',100/100/100',...
    'xoff','0i',...
    'yoff','0i',...
    'isov',1,...
    'iscon',1,...
    'xstep','2f3',...
    'ystep','0.1',...
    'snew','SnW',...
    'linestyle',',-.-',...
    'proj',' -J ');
%
gmt_pstext(...
    'text_x',num2str(min(alpha)+0.005),...
    'text_y',num2str(1-0.065),...
    'text_string','(a)',...
    'text_outps',[outname,'.ps'],...
    'text_fontcolor','255/255/255',...
    'text_backcolor','0/0/0',...
    'text_iscon',1,...
    'text_size',text_size);
%
gmt_psxy4line([alpha,vfun],...
    'outps',[outname,'.ps'],...
    'gmt_lwid','0.08c',...
    'linecolor',',150/150/150',...
    'xoff','0i',...
    'yoff','0i',...
    'isov',1,...
    'iscon',1,...
    'xstep','3f3',...
    'ystep','0.1',...
    'snew','E',...
    'linestyle','',...
    'ytitle','log( @~x  +  y@ )',...
    'proj',' -J ');
%

%
gmt_cptname_top = gmt_optimaldipalpha(outname,...
    'gmt_proj',gmt_proj,...
    'gmt_outps',[outname,'.ps'],...
    'gmt_xsize',gmt_xsize,...
    'gmt_ysize',gmt_ysize,...
    'gmt_xoff','3.7i',...
    'gmt_yoff','0i',...
    'gmt_snew','SnEw',...
    'czinterv','1',...
    'text_size',text_size,...
    'text_string','(b)',...
    'gmt_backgroud','  ',...
    'gmt_isov',1,...
    'gmt_colorbarannosize','5p',...
    'ctitle','Log',...
    'czinterv','0.5',...
    'gmt_iscon',1,...
    'gmt_axstep','4f4',...
    'gmt_iscolorbar',0,...
    'gmt_iscolorbar',gmt_iscolorbar,...
    'gmt_aystep','2f3');
%
gmt_psscale(...
    'gmt_outps',[outname,'.ps'],...
    'gmt_isov',1,...
    'gmt_iscon',0,...
    'gmt_cptname',gmt_cptname_top,...
    'gmt_xshift','2.4i',...
    'gmt_yshift','0.25i',...
    'gmt_lens','0.6i',...
    'gmt_barhigh','0.05i',...
    'gmt_scaledir','h',...
    'gmt_annosize','6p',...
    'gmt_zinterv','0.3',...
    'gmt_background',[103.15,0.99,0.99,0.3],... % for new case ,value should be changed, by FWP
    'gmt_unit','Log');