function gmt_sartrackinfo(vlon,vlat,azi,gmt_outps,varargin)
%
%
% Created by FWP, @ UoG, 2011-10-01
% Updated by Feng, W.P., @ Yj, 2015-05-20
%
%
gmt_lengthscale = '0.5';
gmt_fontsize    = '9p';
lenv            = 4;
for ni = 1:2:numel(varargin)
    par = varargin{ni};
    val = varargin{ni+1};
    eval([par,'=val;']);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
standarddata = [vlon,vlat,lenv.*sind(360+azi),lenv.*cosd(360+azi),0,0,0.00001];
%
gmt_psvelo('gmt_datainp',standarddata,...
    'gmt_outps',   gmt_outps,...
    'gmt_scale',   gmt_lengthscale,...
    'gmt_lcolor',  ',0/0/0',...
    'gmt_lwid',    '0.01c',...
    'gmt_model',   '',...
    'gmt_vecpar',  '15p+a60+g0/0/0+p2.0p+e+l');
%
if azi < -160
    xoff = 0.05;
    yoff = -0.0125;
else
    xoff = -0.05;
    yoff =  0.0125;
end
%
gmt_pstext(...
    'text_x',         num2str(vlon+xoff),...
    'text_y',         num2str(vlat+yoff),...
    'text_string',    'Flight Dir',...
    'text_isov',      1,...
    'text_fontno',    '7',...
    'text_size',      gmt_fontsize,...
    'text_angle',     num2str(-azi+90),...
    'text_edgewidth', '',...
    'text_iscon',     1,...
    'text_backcolor', '',...
    'text_fontcolor', 'black,-=0.25p,255/255/255',...
    'text_fillcolor', '',...
    'text_outps',     gmt_outps);
lenv = 2;
standarddata = [vlon,vlat,lenv.*sind(360+azi+90),lenv.*cosd(360+azi+90),0,0,0.00001];
gmt_psvelo('gmt_datainp',standarddata,...
    'gmt_outps',  gmt_outps,...
    'gmt_scale',  gmt_lengthscale,...
    'gmt_lcolor',  ',0/0/0',...
    'gmt_lwid',   '0.01c',...
    'gmt_vecpar', '15p+a60+g0/0/0+p2.0p+e+r');

return